package gr.aegean.math.explorerlist;

import gr.aegean.math.nodes.SocialNetworkChildren;
import gr.aegean.math.sn.SocialNetwork;
import gr.aegean.math.sn.User;
import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.ListView;
import org.openide.nodes.AbstractNode;
import org.openide.util.Exceptions;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.Lookups;

@ConvertAsProperties(
        dtd = "-//gr.aegean.math.explorerlist//list//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "listTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "gr.aegean.math.explorerlist.listTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_listAction",
        preferredID = "listTopComponent"
)
@Messages({
    "CTL_listAction=list",
    "CTL_listTopComponent=list Window",
    "HINT_listTopComponent=This is a list window"
})
public final class listTopComponent extends TopComponent implements ExplorerManager.Provider, LookupListener {

    private final ListView listView;

    public listTopComponent() {
        initComponents();
        setName(Bundle.CTL_listTopComponent());
        setToolTipText(Bundle.HINT_listTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_SLIDING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
        listView = new ListView();
        setLayout(new BorderLayout());
        add(listView, BorderLayout.CENTER);
        // This is important for lookup purposes...
        associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));
        SocialNetwork sn = new SocialNetwork();
        SocialNetworkChildren snn = new SocialNetworkChildren();
        User u = new User("U1", "18-01-1970", "u1@mail.com");
        users.add(u);
        User s = new User("U2", "20-02-1965", "u2@mail.com");
        users.add(s);
        User t = new User("U3", "11-07-2001", "u3@mail.com");
        users.add(t);
        u.addFriend(s);
        u.addFriend(t);
        snn.refreshList(users);
        AbstractNode snNode = new AbstractNode(snn, Lookups.singleton(sn));
        explorerManager.setRootContext(snNode);
        explorerManager.getRootContext().setDisplayName("NetworkUsers");
        try {
            explorerManager.setSelectedNodes(new AbstractNode[]{snNode});
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    List<User> users = new ArrayList<User>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private transient final ExplorerManager explorerManager = new ExplorerManager();

    @Override
    public ExplorerManager getExplorerManager() {
        //System.out.println("Pressed");
        return explorerManager;
    }

    @Override
    public void resultChanged(LookupEvent le) {
        System.out.println("Pressed");
    }
}
