package gr.aegean.math.friendsdisplay;

import gr.aegean.math.nodes.*;
import gr.aegean.math.sn.*;
import java.awt.BorderLayout;
import java.util.Collection;
import javax.swing.table.TableColumnModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.swing.etable.ETableColumn;
import org.netbeans.swing.etable.ETableColumnModel;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.ListView;
import org.openide.explorer.view.OutlineView;
import org.openide.explorer.view.TableView;

import org.openide.nodes.AbstractNode;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//gr.aegean.math.friendsdisplay//friendsdisplay//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "friendsdisplayTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "gr.aegean.math.friendsdisplay.friendsdisplayTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_friendsdisplayAction",
        preferredID = "friendsdisplayTopComponent"
)
@Messages({
    "CTL_friendsdisplayAction=friendsdisplay",
    "CTL_friendsdisplayTopComponent=friendsdisplay Window",
    "HINT_friendsdisplayTopComponent=This is a friendsdisplay window"
})
public final class friendsdisplayTopComponent extends TopComponent implements LookupListener, ExplorerManager.Provider {

    ListView listView;
    OutlineView outlineView;
    TableView tableView; //Does not work / undocumented...

    private Lookup.Result result = null;

    public friendsdisplayTopComponent() {
        initComponents();
        setName(Bundle.CTL_friendsdisplayTopComponent());
        setToolTipText(Bundle.HINT_friendsdisplayTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);
//        listView = new ListView();

        result = Utilities.actionsGlobalContext().lookupResult(User.class);
        AbstractNode snNode = new AbstractNode(snn);
        explorerManager.setRootContext(snNode);

//        tableModel.setNodes(snn.getNodes());
//        listView = new ListView();
        outlineView = new OutlineView();
        outlineView.setPropertyColumns("username", "Name", "birthday", "Birthday", "mail", "Email");
 
        org.netbeans.swing.outline.Outline outline = outlineView.getOutline();
        outline.setRootVisible(false);
        TableColumnModel columnModel = outline.getColumnModel();
        ETableColumn column = (ETableColumn) columnModel.getColumn(0);
        ((ETableColumnModel) columnModel).setColumnHidden(column, true);
        setLayout(new BorderLayout());
        add(outlineView, BorderLayout.CENTER);

        result.addLookupListener(this);
//        associateLookup(ExplorerUtils.createLookup(explorerManager, getActionMap()));
    }
    SocialNetworkChildren snn = new SocialNetworkChildren();
    AbstractNode snNode;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {

    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    private transient final ExplorerManager explorerManager = new ExplorerManager();

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public void resultChanged(LookupEvent lookupEvent) {
        Lookup.Result r = (Lookup.Result) lookupEvent.getSource();
        Collection<User> coll = r.allInstances();
        if (!coll.isEmpty()) {
            for (User us : coll) {
                snn.refreshList(us.getFriends());

            }
        }
    }
}
